-- DropForeignKey
ALTER TABLE "TB_FLIGHTS" DROP CONSTRAINT "TB_FLIGHTS_pilot_id_fkey";

-- DropForeignKey
ALTER TABLE "TB_FLIGHTS" DROP CONSTRAINT "TB_FLIGHTS_route_id_fkey";

-- DropForeignKey
ALTER TABLE "TB_ROUTES" DROP CONSTRAINT "TB_ROUTES_userId_fkey";

-- AddForeignKey
ALTER TABLE "TB_ROUTES" ADD CONSTRAINT "TB_ROUTES_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TB_USERS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_FLIGHTS" ADD CONSTRAINT "TB_FLIGHTS_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "TB_ROUTES"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_FLIGHTS" ADD CONSTRAINT "TB_FLIGHTS_pilot_id_fkey" FOREIGN KEY ("pilot_id") REFERENCES "TB_USERS"("id") ON DELETE CASCADE ON UPDATE CASCADE;
